import internal1 from '../img/internal1.jpeg'

const volunteers = [{
        id: 1,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 1",
        alt: "cfb1",
        hyperLinkRefernce: "",
    },
    {
        id: 2,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 2",
        alt: "cfb2",
        hyperLinkRefernce: "",
    },
    {
        id: 3,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 3",
        alt: "cfb3",
        hyperLinkRefernce: "#",
    },
    {
        id: 4,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 4",
        alt: "cfb4",
        hyperLinkRefernce: "#",
    },
    {
        id: 5,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 5",
        alt: "cfb5",
        hyperLinkRefernce: "#",
    },
    {
        id: 6,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 6",
        alt: "cfb6",
        hyperLinkRefernce: "#",
    },
    {
        id: 7,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 7",
        alt: "cfb7",
        hyperLinkRefernce: "#",
    },
    {
        id: 8,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 8",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 9,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 10,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 11,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 12,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 13,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 14,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 15,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },
    {
        id: 16,
        image: internal1,
        buttonname: "volunteername",
        heading6: "heading 9",
        alt: "cfb8",
        hyperLinkRefernce: "#",
    },

];
export default volunteers;