import internal1 from '../img/internal1.jpeg'

const volunteers = [{
        id: 1,
        image: internal1,
        buttonname: "Anmol Kumar",
        heading6: "Web Security and Testing,Cyber Security",
        alt: "cfb1",
        hyperLinkRefernce: "www.linkedin.com/in/anmolkumar3244",
    },
    {
        id: 2,
        image: internal1,
        buttonname: "Ajay Uppu",
        heading6: "Threat Intelligence, Cloud Development",
        alt: "cfb2",
        hyperLinkRefernce: "https://www.linkedin.com/in/ajayuppu/",
    },
    {
        id: 3,
        image: internal1,
        buttonname: "AKASH DEEP",
        heading6: "Digital Forensics Department",
        alt: "cfb3",
        hyperLinkRefernce: "linkedin.com/in/akash-deep-82a954140",
    },
    {
        id: 4,
        image: internal1,
        buttonname: "Ankit Bishnoi",
        heading6: "Cyber Security, Digital Forensics",
        alt: "cfb4",
        hyperLinkRefernce: "https://www.linkedin.com/in/ankit-bishnoi-0819",
    },
    {
        id: 5,
        image: internal1,
        buttonname: "CHIRANJEEVEE DOHARE",
        heading6: "Digital Forensics, Forensic Science,  (R&D)",
        alt: "cfb5",
        hyperLinkRefernce: "https://www.linkedin.com/in/chiranjeevee-d-770552147",
    },
    {
        id: 6,
        image: internal1,
        buttonname: "Dimple Rajesh Shah",
        heading6: "Web Security and Testing, Cyber Security",
        alt: "cfb6",
        hyperLinkRefernce: "https://www.linkedin.com/in/dimple-shah-26979753/",
    },
    {
        id: 7,
        image: internal1,
        buttonname: "Gaurav Narula",
        heading6: "Web Security and Testing, Cyber Security, (R&D)",
        alt: "cfb7",
        hyperLinkRefernce: "https://www.linkedin.com/in/gaurav-narula-40152b172/",
    },
    {
        id: 8,
        image: internal1,
        buttonname: "Hizana Farhath",
        heading6: "Forensic Science,(R&D), Content Writing",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/hizana-farhath-4a8158211",
    },
    {
        id: 9,
        image: internal1,
        buttonname: "Dharanidharan KS",
        heading6: "Cyber Security, Digital Forensics",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/dharanidharan-ks-47b71b204",
    },
    {
        id: 10,
        image: internal1,
        buttonname: "Siddharth mahla",
        heading6: "Web Security and Testing Department",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/siddharth-mahla-848386157",
    },
    {
        id: 11,
        image: internal1,
        buttonname: "Neelam Upadhyay",
        heading6: "Web Development, Cyber, Cloud Development",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/neelam-upadhyay-8736a3115",
    },
    {
        id: 12,
        image: internal1,
        buttonname: "Prachi Baliyan",
        heading6: "Forensic Science, Research & Development (R&D)",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/prachi-baliyan-34ab9820a",
    },
    {
        id: 13,
        image: internal1,
        buttonname: "Rajnish Kumar",
        heading6: "Web Development, Web (S&T),Threat Intelligence",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/rajnish-kumar-eh",
    },
    {
        id: 14,
        image: internal1,
        buttonname: "Yukta Sharma ",
        heading6: "Forensic Science department",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/yukta-sharma-b70a9a184",
    },
    {
        id: 15,
        image: internal1,
        buttonname: "Urja Gangwar",
        heading6: "Digital Forensics, Forensic Science,(R&D)",
        alt: "cfb8",
        hyperLinkRefernce: "www.linkedin.com/in/urja-gangwar",
    },
    {
        id: 16,
        image: internal1,
        buttonname: "SIDDHI UPADHYAY",
        heading6: "Forensic Science, Research & Development (R&D)",
        alt: "cfb8",
        hyperLinkRefernce: "https://www.linkedin.com/in/siddhi-upadhyay-a61a221b0",
    },


];
export default volunteers;